/**
 * Cash App Pay API Client
 * 
 * Server-side client for Square Payments API to process Cash App Pay payments.
 * 
 * Note: Cash App Pay requires:
 * 1. Square Developer account
 * 2. Square Application ID (for frontend SDK)
 * 3. Square Access Token (for backend API)
 * 4. Web Payments SDK integration on frontend
 */

import {cashAppConfig} from './config'
import type {
  CashAppPaymentRequest,
  CashAppPaymentResponse,
  CashAppPaymentStatus,
} from './types'

const SQUARE_API_BASE =
  cashAppConfig.environment === 'production'
    ? 'https://connect.squareup.com'
    : 'https://connect.squareupsandbox.com'

export class CashAppClient {
  private accessToken: string
  private locationId?: string

  constructor(config?: {
    accessToken?: string
    locationId?: string
  }) {
    this.accessToken = config?.accessToken || cashAppConfig.accessToken || ''
    this.locationId = config?.locationId || cashAppConfig.locationId
  }

  /**
   * Create a payment request for Cash App Pay
   * 
   * This creates a payment request that can be used with Square's Web Payments SDK
   * on the frontend. The frontend SDK handles the actual payment flow.
   */
  async createPaymentRequest(
    request: CashAppPaymentRequest,
  ): Promise<CashAppPaymentResponse> {
    try {
      if (!this.accessToken) {
        return {
          success: false,
          error:
            'Square access token not configured. Please set SQUARE_ACCESS_TOKEN environment variable.',
        }
      }

      // Convert cents to dollars for Square API
      const amountInDollars = (request.amountCents / 100).toFixed(2)

      // Square Payments API endpoint
      const endpoint = `${SQUARE_API_BASE}/v2/payments`

      // Create payment request body
      const paymentRequest = {
        source_id: 'CASH_APP', // Cash App Pay source
        idempotency_key: `cashapp_${request.orderId}_${Date.now()}`,
        amount_money: {
          amount: request.amountCents, // Square API uses cents
          currency: request.currency || 'USD',
        },
        order_id: request.orderId,
        ...(request.email && {buyer_email_address: request.email}),
        ...(request.phone && {buyer_phone_number: request.phone}),
      }

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Square-Version': '2023-10-18', // Use latest stable version
          Authorization: `Bearer ${this.accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(paymentRequest),
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        return {
          success: false,
          error:
            errorData.errors?.[0]?.detail ||
            `Square API error: ${response.status}`,
        }
      }

      const data = await response.json()

      // For Cash App Pay, the frontend SDK handles the payment flow
      // This endpoint is mainly for creating payment intents
      // The actual payment URL/QR code is generated by the frontend SDK

      return {
        success: true,
        paymentId: data.payment?.id,
      }
    } catch (error) {
      return {
        success: false,
        error:
          error instanceof Error
            ? error.message
            : 'Failed to create Cash App payment request',
      }
    }
  }

  /**
   * Check payment status
   */
  async checkPaymentStatus(
    paymentId: string,
  ): Promise<CashAppPaymentStatus | null> {
    try {
      if (!this.accessToken) {
        return null
      }

      const endpoint = `${SQUARE_API_BASE}/v2/payments/${paymentId}`

      const response = await fetch(endpoint, {
        method: 'GET',
        headers: {
          'Square-Version': '2023-10-18',
          Authorization: `Bearer ${this.accessToken}`,
        },
      })

      if (!response.ok) {
        return null
      }

      const data = await response.json()
      const payment = data.payment

      return {
        status: this.mapSquareStatusToCashAppStatus(payment.status),
        paymentId: payment.id,
        transactionId: payment.transaction_id,
        paidAt: payment.updated_at
          ? new Date(payment.updated_at).getTime()
          : undefined,
      }
    } catch (error) {
      console.error('Cash App status check error:', error)
      return null
    }
  }

  /**
   * Map Square payment status to Cash App payment status
   */
  private mapSquareStatusToCashAppStatus(
    squareStatus: string,
  ): CashAppPaymentStatus['status'] {
    const statusMap: Record<string, CashAppPaymentStatus['status']> = {
      PENDING: 'pending',
      APPROVED: 'completed',
      COMPLETED: 'completed',
      CANCELED: 'cancelled',
      FAILED: 'failed',
    }

    return statusMap[squareStatus] || 'pending'
  }
}

// Export singleton instance
export const cashAppClient = new CashAppClient()

// Export factory function for custom configuration
export function createCashAppClient(config?: {
  accessToken?: string
  locationId?: string
}): CashAppClient {
  return new CashAppClient(config)
}
