/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/xpriori/Code/hyfe/public/three/model/base.glb --types --transform --draco /tmp/draco 
Files: /Users/xpriori/Code/hyfe/public/three/model/base.glb [5.11MB] > /Users/xpriori/Code/hyfe/base-transformed.glb [313.66KB] (94%)
*/

import * as THREE from 'three'
import React from 'react'
import type {ThreeElements} from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    ['rf-logo-3d']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: ThreeElements['group']) {
  const {nodes, materials} = useGLTF(
    '/base-transformed.glb',
    '/tmp/draco',
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials['rf-logo-3d']} />
    </group>
  )
}

useGLTF.preload('/base-transformed.glb')
