/** @type {import('@react-email/components').TailwindConfig} */
const config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './ctx/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: ['class', '.dark'],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: 'var(--radius)',
        sm: 'calc(var(--radius) - 4px)',
        md: 'calc(var(--radius) - 2px)',
        lg: 'var(--radius)',
        xl: 'calc(var(--radius) + 4px)',
      },
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        accent: 'var(--accent)',
        primary: 'var(--primary)',
        brand: 'var(--brand)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        tertiary: 'var(--tertiary)',
        'tertiary-foreground': 'var(--tertiary-foreground)',
        panel: 'var(--panel)',
        muted: 'var(--muted)',
        border: 'var(--border)',
        hue: 'var(--hue)',
        alum: 'oklch(0.773 0.011 212.53)',
        flavors: 'oklch(0.783 0.168 66.2)',
        terpenes: 'var(--terpenes)',
        effects: 'var(--effects)',
        'sidebar-ring': 'var(--sidebar-ring)',
        'sidebar-border': 'var(--sidebar-border)',
        'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
        'sidebar-accent': 'var(--sidebar-accent)',
        'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
        'sidebar-primary': 'var(--sidebar-primary)',
        'sidebar-foreground': 'var(--sidebar-foreground)',
        sidebar: 'var(--sidebar)',
        'chart-5': 'var(--chart-5)',
        'chart-4': 'var(--chart-4)',
        'chart-3': 'var(--chart-3)',
        'chart-2': 'var(--chart-2)',
        'chart-1': 'var(--chart-1)',
        ring: 'var(--ring)',
        input: 'var(--input)',
        destructive: 'var(--destructive)',
        'accent-foreground': 'var(--accent-foreground)',
        'muted-foreground': 'var(--muted-foreground)',
        'popover-foreground': 'var(--popover-foreground)',
        popover: 'var(--popover)',
        'card-foreground': 'var(--card-foreground)',
        card: 'var(--card)',
        'light-gray': 'oklch(0.802 0 0)',
        'dark-gray': 'oklch(0.314 0.001 17.23)',
        origin: 'oklch(0.215 0.006 285.9)',
        vim: 'oklch(0.196 0.021 271.47)',
        'dark-table': 'oklch(0.348 0.021 277.79)',
        'light-table': 'oklch(0.881 0.01 286.2)',
        cashapp: 'oklch(0.8251 0.2644 143.87)',
        featured: 'oklch(0.755 0.153 231.64)',
        limited: 'oklch(0.931 0.228 122.86)',
        rare: 'oklch(0.585 0.204 277.12)',
        deal: 'oklch(0.704 0.123 182.5)',
        'mac-blue': 'var(--mac-blue)',
        robinhood: 'oklch(0.9301 0.229 123.31)',
        unlimit: 'oklch(0.9124 0.207 122.95)',
        moonpay: 'oklch(0.5272 0.293 292.95)',
        rampnetwork: 'oklch(0.7102 0.1663 155.57)',
        usdc: 'oklch(0.562 0.1504 253.19)',
        polygon: 'oklch(0.5284 0.2186 291.48)',
        ethereum: 'oklch(0.6416 0.1738 268.95)',
        bitcoin: 'oklch(0.7523 0.1663 62.59)',
        usdt: 'oklch(0.6346 0.1184 167.54)',
      },
      fontFamily: {
        'geist-sans': 'var(--font-geist-sans)',
        mono: 'var(--font-geist-mono)',
        space: 'var(--font-space)',
        fugaz: 'var(--font-fugaz)',
        sans: 'var(--font-sans)',
        bone: 'var(--font-bone)',
        nito: 'var(--font-nito)',
        brk: ['BrkMono', 'Menlo', 'Helvetica', 'monospace'],
        ios: ['IoskeleyMono', 'Menlo', 'Helvetica', 'monospace'],
        polysans: ['PolySans', 'Arial', 'Helvetica', 'sans-serif'],
        'polysans-wide': ['PolySansWide', 'Arial', 'Helvetica', 'sans-serif'],
        neusans: ['NeuSans', 'Arial', 'Helvetica', 'sans-serif'],
        okxs: ['Okxs', 'Helvetica', 'sans-serif'],
        clash: ['ClashGrotesk', 'Helvetica', 'sans-serif'],
        monaco: ['Monaco', 'Helvetica', 'sans-serif'],
        'pixel-sqr': 'GeistPixelSquare',
        'pixel-cir': 'GeistPixelCircle',
        'pixel-tri': 'GeistPixelTriangle',
        'pixel-grid': 'GeistPixelGrid',
        'pixel-line': 'GeistPixelLine',
      },
    },
  },
  // Tailwind v4 is CSS-first: theme is in app/globals.css via @theme; HeroUI via @plugin and @source there.
  // This file is for tooling (e.g. IntelliSense) and as a JS reference of the theme.
  plugins: [],
}

export default config
