export const CSV_DENOM_KEYS = [
  '0.125',
  '0.25',
  '0.5',
  '1',
  '2',
  '3',
  '3.5',
  '4',
  '5',
  '6',
  '7',
  '8',
] as const

export const PRODUCT_CSV_FIELDS = [
  '_id',
  '_creationTime',
  'name',
  'slug',
  'base',
  'categoryId',
  'categorySlug',
  'shortDescription',
  'description',
  'priceCents',
  'unit',
  'availableDenominations',
  'popularDenomination',
  'thcPercentage',
  'cbdPercentage',
  'effects',
  'terpenes',
  'limited',
  'featured',
  'available',
  'stock',
  'inventoryMode',
  'masterStockQuantity',
  'masterStockUnit',
  'stockByDenomination',
  'priceByDenomination',
  'salePriceByDenomination',
  'rating',
  'image',
  'gallery',
  'consumption',
  'flavorNotes',
  'potencyLevel',
  'potencyProfile',
  'weightGrams',
  'brand',
  'lineage',
  'noseRating',
  'variants',
  'tier',
  'eligibleForRewards',
  'eligibleForDeals',
  'onSale',
  'eligibleDenominationForDeals',
  'eligibleForUpgrade',
  'upgradePrice',
  'dealType',
  'productType',
  'strainType',
  'netWeight',
  'netWeightUnit',
  'highMargins',
  'brandCollaborators',
  'tags',
  'packagingMode',
  'stockUnit',
  'packSize',
  'startingWeight',
  'remainingWeight',
  'subcategory',
  'batchId',
  'archived',
] as const

export const DENOM_HEADERS = CSV_DENOM_KEYS.flatMap((key) => [
  `price_${key}`,
  `stock_${key}`,
])

export const EXPECTED_CSV_HEADERS = [...PRODUCT_CSV_FIELDS, ...DENOM_HEADERS]
