export const ipapi_response = {
  ip: '91.196.152.100',
  type: 'ipv4',
  continent_code: 'EU',
  continent_name: 'Europe',
  country_code: 'FR',
  country_name: 'France',
  region_code: 'FR-59',
  region_name: 'Nord',
  city: 'Lille',
  zip: '59000',
  latitude: 50.6292991638184,
  longitude: 3.05699992179871,
  msa: null,
  dma: null,
  radius: '0',
  ip_routing_type: null,
  connection_type: null,
  location: {
    geoname_id: 6454414,
    capital: 'Paris',
    languages: [
      {
        code: 'fr',
        name: 'French',
        native: 'Français',
      },
    ],
    country_flag: 'https://assets.ipstack.com/flags/fr.svg',
    country_flag_emoji: '🇫🇷',
    country_flag_emoji_unicode: 'U+1F1EB U+1F1F7',
    calling_code: '33',
    is_eu: true,
  },
}
